version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "gitdb"
      - dependency-name: "jmespath"
      - dependency-name: "six"


