version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "sentry-sdk"
      - dependency-name: "boto3"
      - dependency-name: "pytest-cov"


