version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "sentry-sdk"
      - dependency-name: "jmespath"
      - dependency-name: "protobuf"
      - dependency-name: "pydash"
      - dependency-name: "numpy"
      - dependency-name: "pluggy"
