# Add 'repo' label to any root file changes
repo:
- '*'

terraform:
- any: [
    '**/*.tf',
]

docker-critical-vulnerability:
  - any: [ '**/.docker.critical', ]
docker-high-vulnerability:
  - any: [ '**/.docker.high', ]
docker-medium-vulnerability:
  - any: [ '**/.docker.medium', ]
docker-low-vulnerability:
  - any: [ '**/.docker.low', ]
