name: "Custom Github Action for update branch"
description: "Update the head branch with the base branch of a pull request"
inputs:
  gh_token:
    description: "The GitHub token for executing the action"
    required: true

runs:
  using: "composite"
  steps:
    - run: | 
        echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name : Checkout
      uses: actions/checkout@v4
    - name: Update head branch with base branch
      run: update_branch.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
    - name: Get PR number
      id: pr_number
      uses: intuitivo-ai/in2-actions//get_pr_number@action_update_branch
      with:
        gh_token: ${{ inputs.gh_token }}
    - name: Desposal branch
      run: update_branch.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
        PR_NUMBER: ${{ steps.pr_number.outputs.pr_number }}