name: "Custom Github Action for update branch"
description: "Update the head branch with the base branch of a pull request"
inputs:
  gh_token:
    description: "The GitHub token for executing the action"
    required: true
  new_branch_name:
    description: "The new branch name"
    required: false

runs:
  using: "composite"
  steps:
    - run: | 
        echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Get PR number
      id: pr_number
      uses: intuitivo-ai/in2-github-actions-test//get_pr_number@follow_pr
      with:
        gh_token: ${{ inputs.gh_token }}
    - name: Update head branch with base branch
      run: update_branch.sh
      shell: bash
      env:
        BRANCH_NAME: ${{ steps.pr_number.outputs.branch_name }}
        GITHUB_TOKEN: ${{ inputs.gh_token }}
        NEW_BRANCH_NAME: ${{ inputs.new_branch_name }}
        PR_NUMBER: ${{ steps.pr_number.outputs.pr_number }}
    - name: Desposal branch
      run: python $GITHUB_ACTION_PATH/open_delete_branch.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
