name: "Custom GitHub Action Composite for Get pr number"
description: "Pull Request Number"

inputs:
  gh_token:
    description: "The GitHub token for executing the action"
    required: true
outputs:
  pr_number:
    description: 'Pr number Output'
    value: ${{ steps.pr_number.outputs.pr_number }}
  branch_name:
    description: 'Branch name Output'
    value: ${{ steps.pr_number.outputs.branch_name }}

runs:
  using: "composite"
  steps:
    - run: | 
        echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name : Get pr number
      id: pr_number
      run: get_pr_number.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
