name: Build

on:
  workflow_dispatch:
  push:

env:
  REGISTRY: 'registry.com'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        id: build
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.GITHUB_REPOSITORY }}
      - name: Common
        uses: ./.github/common-action
        id: common-action
        with:
          digest: ${{ steps.build.outputs.digest }}
      - run: echo ${{ steps.common-action.outputs.IMAGE_ID }}
  hello_world_job:
    if: ${{ contains( github.ref, 'master') }}
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./.github/action1 # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
  build1:
    if: ${{ contains( github.ref, 'master') }}
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./.github/workflows/docker-build.yml
        with:
          github_organization: ${GITHUB_REPOSITORY_OWNER}
      - name: push
        uses: ./.github/workflows/docker-push-ecr.yml
        with:
          branch: "branch"
          commit_id: ${{ needs.build.outputs.commit_id }}
          registry: "registry"
          repository: ${{ needs.build.outputs.repository }}

  test:
    runs-on: ubuntu-latest
    needs: build1
    steps:
      - run: echo ${{ needs.build.outputs.image_id }}
