name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./.github/workflows/docker-build.yml
        with:
          github_organization: ${GITHUB_REPOSITORY_OWNER}
      - name: push
        uses: ./.github/workflows/docker-push-ecr.yml
        with:
          branch: "branch"
          commit_id: ${{ needs.build.outputs.commit_id }}
          registry: "registry"
          repository: ${{ needs.build.outputs.repository }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{ needs.build.outputs.image_id }}
