name: Build

on:
  workflow_dispatch:
  push:

env:
  REGISTRY: 'registry.com'

jobs:
  build-action:
    if: ${{ contains( github.ref, 'master') }}
    runs-on: ubuntu-latest
    name: Build
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build using actions
        uses: ./.github/docker/build
        id: build-action
        with:
          github_organization: $GITHUB_REPOSITORY_OWNER
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./.github/action1 # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: ${{ format('{0}/{1}:{2}', env.REGISTRY, steps.hello.outputs.REPOSITORY, steps.hello.outputs.COMMIT_ID) }}
  build:
    if: ${{ contains( github.ref, 'master') }}
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./.github/workflows/docker-build.yml
        with:
          github_organization: ${GITHUB_REPOSITORY_OWNER}
      - name: push
        uses: ./.github/workflows/docker-push-ecr.yml
        with:
          branch: "branch"
          commit_id: ${{ needs.build.outputs.commit_id }}
          registry: "registry"
          repository: ${{ needs.build.outputs.repository }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{ needs.build.outputs.image_id }}
