name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{ needs.build.outputs.image }}
