name: Continuous Integration

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      AWS_REGION: us-east-1
      DEFAULT_DOCKER_TAG: in2etvo
      PUSH: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.ECR_REGISTRY }}
  test:
    needs: build
    uses: ./.github/workflows/unit-tests.yml
    with:
      AWS_REGION: us-east-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.ECR_REGISTRY }}
  migrations:
    needs: build
    if: ${{ environment.RUN_MIGRATIONS }}
    uses: ./.github/workflows/migrations.yml
    with:
      AWS_REGION: us-east-1
      RUN_MIGRATIONS: true
      TEST: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.ECR_REGISTRY }}
