name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  build:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      AWS_REGION: us-east-2
      DEFAULT_DOCKER_TAG: in2etvo
      PUSH: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.ECR_REGISTRY }}
  test:
    uses: ./.github/workflows/unit-tests.yml
    with:
      AWS_REGION: us-east-2
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.ECR_REGISTRY }}
