name: Continuous Delivery

on:
  push:
    branches:
      - main
      - add_tags
  workflow_dispatch:
    inputs:
      ACTION:
        description: ""
        required: true
        default: plan
        type: choice
        options:
          - plan
          - deploy
      ENVIRONMENT:
        description: ""
        required: false
        default: staging
        type: choice
        options:
          - development
          - staging

jobs:
  config:
    name: Config
    uses: ./.github/workflows/pre.yml
    with:
      DEFAULT_ENVIRONMENT: staging
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
  build:
    if: ${{ github.event_name == 'push' }}
    needs: config
    name: Build
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      AWS_REGION: us-east-1
      PUBLISH: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.ECR_REGISTRY }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    if: ${{ github.event_name == 'push' }}
    needs: build
    name: Tests
    uses: ./.github/workflows/unit-tests.yml
    with:
      AWS_REGION: us-east-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.ECR_REGISTRY }}
  migrations:
    needs: build
    name: Tests
    uses: ./.github/workflows/migrations.yml
    with:
      AWS_REGION: us-east-1
      RUN_MIGRATIONS: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.ECR_REGISTRY }}
  development_plan:
    if: ${{ (github.event_name == 'push' || needs.config.outputs.environment == 'development') }}
    name: Development
    needs:
      - config
    uses: ./.github/workflows/terraform-plan.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: development
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  development-manualdeploy:
    if: ${{ (inputs.ACTION == 'deploy' && needs.config.outputs.environment == 'development') }}
    name: Development
    needs:
      - development_plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: development
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  development-autodeploy:
    if: ${{ (github.event_name == 'push' && github.ref_name == 'dev') }}
    name: Development
    needs:
      - config
      - build
      - test
      - migrations
      - development_plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: development
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  staging_plan:
    if: ${{ (github.event_name == 'push' || needs.config.outputs.environment == 'staging') }}
    name: Staging
    needs:
      - config
    uses: ./.github/workflows/terraform-plan.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: staging
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  staging-manualdeploy:
    if: ${{ (inputs.ACTION == 'deploy' && needs.config.outputs.environment == 'staging') }}
    name: Staging
    needs:
      - staging_plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: staging
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  staging-autodeploy:
    #if: ${{ (github.event_name == 'push' && github.ref_name == 'main') }}
    name: Staging
    needs:
      - config
      - build
      - test
      - migrations
      - staging_plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: staging
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  production_plan:
    if: ${{ github.event_name == 'push' }}
    name: Production
    needs:
      - config
    uses: ./.github/workflows/terraform-plan.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: production
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  showroom_plan:
    if: ${{ github.event_name == 'push' }}
    name: Showroom
    needs:
      - config
    uses: ./.github/workflows/terraform-plan.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: showroom
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
