name: Continuous Delivery

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ACTION:
        description: ""
        required: true
        default: plan
        type: choice
        options:
        - plan
        - deploy
      ENVIRONMENT:
        description: ""
        required: false
        default: staging
        type: string

jobs:
  config:
    name: Config
    uses: ./.github/workflows/pre.yml
    with:
      DEFAULT_ENVIRONMENT: staging
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
  build:
    if: ${{ github.event_name == 'push' }}
    needs: config
    name: Build
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      AWS_REGION: us-east-1
      DEFAULT_DOCKER_TAG: in2etvo
      PUSH: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.ECR_REGISTRY }}
  test:
    if: ${{ github.event_name == 'push' }}
    needs: build
    name: Tests
    uses: ./.github/workflows/unit-tests.yml
    with:
      AWS_REGION: us-east-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.ECR_REGISTRY }}
  migrations:
    needs: build
    name: Migrations
    uses: ./.github/workflows/migrations.yml
    with:
      AWS_REGION: us-east-1
      TEST: true
      RUN_MIGRATIONS: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGISTRY: ${{ secrets.ECR_REGISTRY }}
  staging_plan:
    if: ${{ github.event_name == 'push' || needs.config.outputs.environment == 'staging' }}
    name: Staging
    needs:
     - config
    uses: ./.github/workflows/terraform-plan.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: staging
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  staging-manualdeploy:
    if: ${{ inputs.ACTION == 'deploy' && needs.config.outputs.environment == 'staging' }}
    name: Staging
    needs:
      - staging_plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: ${{ needs.config.outputs.environment }}
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  staging-autodeploy:
    if: ${{ (github.event_name == 'push' && github.ref_name == 'main') || (inputs.ACTION == 'deploy' && needs.config.outputs.environment == 'staging') }}
    name: Staging
    needs:
     - build
     - test
     - migrations
     - config
     - staging_plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: ${{ needs.config.outputs.environment }}
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  production_plan:
    if: ${{ github.event_name == 'push' }}
    name: Production
    needs:
     - config
    uses: ./.github/workflows/terraform-plan.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: production
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
