name: Release

on:
  workflow_call:

jobs:
  create_release:
    runs-on: [ self-hosted, linux, intuitivo ]
    name: Create Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release Notes
        id: release_notes        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./scripts/*
          ./scripts/release_notes.sh
