name: Deploy to Production (Manual)

on:
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ contains( github.ref, 'main') }}
    uses: ./.github/workflows/terraform-apply.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: production
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
