name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  plan:
#    if: ${{ contains( github.ref, 'master') }}
    uses: ./.github/workflows/terraform-plan.yml
    with:
      AWS_REGION: us-east-2
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  deploy:
    if: ${{ contains( github.ref, 'main') || contains( github.ref, 'dev') }}
    needs: plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      AWS_REGION: us-east-2
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
