
name: Deploy to Critical Environments

on:
  workflow_dispatch:
    inputs:
      ACTION:
        description: ""
        required: true
        default: plan
        type: choice
        options:
          - plan
          - deploy
      ENVIRONMENT:
        description: ""
        required: true
        default: showroom
        type: choice
        options:
          - production
          - showroom
    
jobs:
  config:
    name: Config
    uses: ./.github/workflows/pre.yml
    with:
      DEFAULT_ENVIRONMENT: showroom
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
  
  production_plan:
    if: ${{ needs.config.outputs.environment == 'production' }}
    name: production
    strategy:
      fail-fast: false
      matrix:
        env: [ production ]
        region: [ us-east-1, sa-east-1 ]
    needs:
      - config
    uses: ./.github/workflows/terraform-plan.yml
    with:
      AWS_REGION: ${{ matrix.region }}
      ENVIRONMENT: ${{ matrix.env }}
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  production_deploy:
    if: ${{ inputs.ACTION == 'deploy' && github.ref_name == 'main' && github.ref_type == 'branch' && needs.config.outputs.environment == 'production' }}
    name: production
    strategy:
      fail-fast: false
      matrix:
        env: [ production ]
        region: [ us-east-1, sa-east-1 ]
    needs:
      - config
      - production_plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      AWS_REGION: ${{ matrix.region }}
      ENVIRONMENT: ${{ matrix.env }}
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  showroom_plan:
    if: ${{ needs.config.outputs.environment == 'showroom' }}
    name: showroom
    strategy:
      fail-fast: false
      matrix:
        env: [ showroom ]
        region: [ us-east-1, sa-east-1 ]
    needs:
      - config
    uses: ./.github/workflows/terraform-plan.yml
    with:
      AWS_REGION: ${{ matrix.region }}
      ENVIRONMENT: ${{ matrix.env }}
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  showroom_deploy:
    if: ${{ inputs.ACTION == 'deploy' && github.ref_name == 'main' && github.ref_type == 'branch' && needs.config.outputs.environment == 'showroom' }}
    name: showroom
    strategy:
      fail-fast: false
      matrix:
        env: [ showroom ]
        region: [ us-east-1, sa-east-1 ]
    needs:
      - config
      - showroom_plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      AWS_REGION: ${{ matrix.region }}
      ENVIRONMENT: ${{ matrix.env }}
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  release:
    name: Release
    needs:
      - production_deploy
    uses: ./.github/workflows/create-release-prod.yml