name: Deploy to Critical Environments

on:
  workflow_dispatch:
    inputs:
      ACTION:
        description: ""
        required: true
        default: plan
        type: choice
        options:
          - plan
          - deploy
      ENVIRONMENT:
        description: ""
        required: true
        default: showroom
        type: choice
        options:
          - production
          - showroom

jobs:
  config:
    name: Config
    uses: ./.github/workflows/pre.yml
    with:
      DEFAULT_ENVIRONMENT: showroom
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
  production_plan:
    if: ${{ needs.config.outputs.environment == 'production' }}
    name: Production
    needs:
      - config
    uses: ./.github/workflows/terraform-plan.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: production
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  production_deploy:
    if: ${{ inputs.ACTION == 'deploy' && github.ref_name == 'main' && github.ref_type == 'branch' && needs.config.outputs.environment == 'production' }}
    name: Production
    needs:
      - config
      - production_plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: production
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  showroom_plan:
    if: ${{ needs.config.outputs.environment == 'showroom' }}
    name: Showroom
    needs:
      - config
    uses: ./.github/workflows/terraform-plan.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: showroom
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  showroom_deploy:
    if: ${{ inputs.ACTION == 'deploy' && github.ref_name == 'main' && github.ref_type == 'branch' && needs.config.outputs.environment == 'showroom' }}
    name: Showroom
    needs:
      - config
      - showroom_plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: showroom
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
