name: Deploy to Staging (Manual)

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/terraform-apply.yml
    with:
      AWS_REGION: us-east-2
      ENVIRONMENT: staging
      LAMBDA: true
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
