name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ACTION:
        description: ""
        required: true
        default: plan
        type: choice
        options:
        - plan
        - deploy
      ENVIRONMENT:
        description: ""
        required: true
        default: production
        type: choice
        options:
        - production

jobs:
  config:
    name: Config
    uses: ./.github/workflows/pre.yml
    with:
      DEFAULT_ENVIRONMENT: production
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
  production_plan:
    if: ${{ ( github.ref_name == 'main' && github.ref_type == 'branch' && github.event_name == 'push' ) || needs.config.outputs.environment == 'production' }}
    name: Production
    needs:
     - config
    uses: ./.github/workflows/terraform-plan.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: production
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  production_deploy:
    if: ${{ inputs.ACTION == 'deploy' && github.ref_name == 'main' && github.ref_type == 'branch' && needs.config.outputs.environment == 'production' }}
    name: Production
    needs:
     - config
     - production_plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: ${{ needs.config.outputs.environment }}
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
