name: build

on:
  workflow_dispatch:
  push:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#      - name: Lint
#        run: docker run --rm -i hadolint/hadolint hadolint - < Dockerfile
      - name: Build
        run: docker build .

