name: Docker-Build

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      CHECKOUT_IN2_REPOSITORIES:
        required: false
        type: boolean
        default: false
      CHECKOUT_IN2_REPOSITORY_NAMES:
        required: false
        type: string
      BUILD:
        required: false
        type: string
        default: docker
      PUBLISH:
        required: false
        type: boolean
        default: false
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
      REGISTRY:
        required: false
      TOKEN:
        required: false

env:
  VERSION: "1.5.${{ github.run_number }}"
  NODE_AUTH_TOKEN: ${{ secrets.TOKEN }}
  REGISTRY: ${{ secrets.REGISTRY }}
  DEFAULT_DOCKER_TAG: 'in2etvo'

jobs:
  docker-build-and-push:
    runs-on: [ self-hosted, linux ]
    name: Build and Push
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout ${{ inputs.CHECKOUT_IN2_REPOSITORY_NAMES }} repositories
        if: ${{ inputs.CHECKOUT_IN2_REPOSITORIES }}
        run: |
          ORG="${GITHUB_REPOSITORY_OWNER}"

          ./scripts/checkout_repositories.sh ${ORG} ${{ inputs.CHECKOUT_IN2_REPOSITORY_NAMES }}
      - name: Configure AWS credentials
        if: ${{ inputs.BUILD == 'docker' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Login to Amazon ECR
        if: ${{ inputs.BUILD == 'docker' }}
        uses: aws-actions/amazon-ecr-login@v1
      - name: Setup Node
        if: ${{ inputs.BUILD == 'npm' }}
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@intuitivo-ai'
      - name: Build
        run: |
          ./scripts/build.sh ${{ inputs.BUILD }}
      - name: Publish
        if: ${{ inputs.PUBLISH }}
        run: |
          ./scripts/publish.sh ${{ inputs.BUILD }}
