name: Docker-Build

on:
  workflow_call:
    outputs:
      image:
        description: "The first output string"
        value: ${{ jobs.docker-build.outputs.IMAGE }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      IMAGE: ${{ steps.build.outputs.COMMIT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#      - name: Lint
#        run: docker run --rm -i hadolint/hadolint hadolint - < Dockerfile
      - name: Build
        id:   build
        run:  |
          docker build .
          echo "::set-output name=COMMIT_ID::${GITHUB_SHA}"

