name: Docker-Build

on:
  workflow_call:
    inputs:
      github_organization:
        required: true
        type: string
    outputs:
      image_id:
        value: ${{ jobs.docker-build.outputs.IMAGE_ID }}
      commit_id:
        value: ${{ jobs.docker-build.outputs.COMMIT_ID }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      COMMIT_ID: ${{ steps.build.outputs.COMMIT_ID }}
      IMAGE_ID: ${{ steps.build.outputs.IMAGE_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#      - name: Lint
#        run: docker run --rm -i hadolint/hadolint hadolint - < Dockerfile
      - name: Build
        id: build
        run: |
          REPOSITORY=$(echo ${GITHUB_REPOSITORY} | sed "s|${{ inputs.github_organization }}/||g")
          echo ${REPOSITORY}
          docker build . -t ${GITHUB_REPOSITORY}:${GITHUB_SHA}
          echo "::set-output name=COMMIT_ID::${GITHUB_SHA}"
          echo "::set-output name=IMAGE_ID::${GITHUB_REPOSITORY}:${GITHUB_SHA}"

