name: Docker-Build

on:
  workflow_call:
    inputs:
      github_organization:
        required: true
        type: string
    outputs:
      commit_id:
        value: ${{ jobs.docker-build.outputs.COMMIT_ID }}
      image_id:
        value: ${{ jobs.docker-build.outputs.REPOSITORY }}:${{ jobs.docker-build.outputs.COMMIT_ID }}
      repository:
        value: ${{ jobs.docker-build.outputs.REPOSITORY }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      COMMIT_ID: ${{ steps.build.outputs.COMMIT_ID }}
      REPOSITORY: ${{ steps.build.outputs.REPOSITORY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#      - name: Lint
#        run: docker run --rm -i hadolint/hadolint hadolint - < Dockerfile
      - name: Build
        id: build
        run: |
          REPOSITORY=$(echo ${GITHUB_REPOSITORY} | sed "s|${{ inputs.github_organization }}/||g")
          IMAGE="${REPOSITORY}:${GITHUB_SHA}"
          docker build . -t ${IMAGE}
          echo "::set-output name=COMMIT_ID::${GITHUB_SHA}"
          echo "::set-output name=REPOSITORY::${REPOSITORY}"

