name: Docker-Push-to-ECR

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      commit_id:
        required: true
        type: string
      registry:
        required: true
        type: string
      repository:
        required: true
        type: string

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Tag images
        run: |
          SOURCE="${{ inputs.repository }}:${{ inputs.commit_id }}"
          DESTINATION="${{ inputs.registry }}/${{ inputs.repository }}"
          docker tag ${SOURCE} ${DESTINATION}:${{ inputs.commit_id }}
          docker tag ${SOURCE} ${DESTINATION}:${{ inputs.branch }}
          docker tag ${SOURCE} ${DESTINATION}:${{ inputs.branch }}_${{ inputs.commit_id }}
          docker images
