name: Infracost Report

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      TF_PATH:
        required: false
        type: string
        default: './'
    secrets:
      INFRACOST_API_KEY:
        required: true
      PERSONAL_ACCESS_TOKEN:
        required: false
env:
  VAR_FILE: ${{ inputs.ENVIRONMENT }}-${{ inputs.AWS_REGION }}
  INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

jobs:
  infracost-report:
    runs-on: [ self-hosted, linux, intuitivo ]
    name: Infracost Report
    defaults:
      run:
        working-directory: ${{ inputs.TF_PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download tf plan
        uses: actions/download-artifact@v4
        with:
          name: plan_${{ env.VAR_FILE }}.json
          path: ${{ inputs.TF_PATH }}

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Infracost report
        run: |
          chmod +x ../scripts/*
          ../scripts/infracost_report.sh
