name: Infracost Report

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: false
        type: string
      ENVIRONMENT:
        required: false
        type: string
      GH_SHA:
        required: false
        type: string
      RUN_ON_PR:
        required: false
        default: false
        type: boolean
      TF_PATH:
        required: false
        type: string
        default: './'
    secrets:
      INFRACOST_API_KEY:
        required: true
      GH_TOKEN:
        required: false
      PERSONAL_ACCESS_TOKEN:
        required: false
env:
  VAR_FILE: ${{ inputs.ENVIRONMENT }}-${{ inputs.AWS_REGION }}
  INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

jobs:
  infracost-report:
    runs-on: [ self-hosted, linux, intuitivo ]
    name: Infracost Report
    defaults:
      run:
        working-directory: ${{ inputs.TF_PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download tf plan
        if: ${{ ! inputs.RUN_ON_PR }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.ref_name }}_plan_${{ env.VAR_FILE }}.json
          path: ${{ inputs.TF_PATH }}

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Infracost report
        if: ${{ ! inputs.RUN_ON_PR }}
        run: |
          chmod +x ../scripts/*
          ../scripts/infracost_report.sh ${{ github.ref_name }}_plan_${{ env.VAR_FILE }}.json

      - name: Get CICD workflow run id
        id: get_run_id
        if: ${{ inputs.RUN_ON_PR }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: |
          chmod +x ../scripts/*
          python3 ../scripts/get_run_id.py ${{ github.head_ref }} ${{ inputs.GH_SHA }}

      - name: Download tf plan
        if: ${{ inputs.RUN_ON_PR }}
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          path: ${{ inputs.TF_PATH }}
          run-id: ${{ steps.get_run_id.outputs.run_id }}

      - name: Infracost PR report
        if: ${{ inputs.RUN_ON_PR }}
        run: |
          chmod +x ../scripts/*
          ../scripts/infracost_comment.sh

      - name: Infracost Comment
        if: ${{ inputs.RUN_ON_PR }}
        run: |
          infracost comment github --path=report.json \
                                   --repo=$GITHUB_REPOSITORY \
                                   --github-token=${{ github.token }} \
                                   --pull-request=${{ github.event.pull_request.number }} \
                                   --behavior=update \
                                   --show-all-projects