name: Infracost Report

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: false
        type: string
      ENVIRONMENT:
        required: false
        type: string
      GH_SHA:
        required: false
        type: string
      RUN:
        required: false
        type: string
      RUN_ON_PR:
        required: false
        default: false
        type: boolean
      TF_PATH:
        required: false
        type: string
        default: './'
    secrets:
      INFRACOST_API_KEY:
        required: true
      GH_TOKEN:
        required: false
      PERSONAL_ACCESS_TOKEN:
        required: false
env:
  VAR_FILE: ${{ inputs.ENVIRONMENT }}-${{ inputs.AWS_REGION }}
  INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

jobs:
  infracost-report:
    if: ${{ inputs.RUN == 'true' }}
    runs-on: [ self-hosted, linux, intuitivo ]
    name: Infracost Report
    defaults:
      run:
        working-directory: ${{ inputs.TF_PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get PR number
        if: ${{ inputs.RUN_ON_PR }}
        id: pr_number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ../scripts/*
          ../scripts/get_pr_number.sh

      - name: Download tf plan
        if: ${{ ! inputs.RUN_ON_PR }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.VAR_FILE }}.json
          path: ${{ inputs.TF_PATH }}

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Infracost report
        if: ${{ ! inputs.RUN_ON_PR }}
        run: |
          chmod +x ../scripts/*
          ../scripts/infracost_report.sh ${{ github.ref_name }}_plan_${{ env.VAR_FILE }}.json

      - name: Get CICD workflow run id
        id: get_run_id
        if: ${{ inputs.RUN_ON_PR }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: |
          chmod +x ../scripts/*
          python3 ../scripts/get_run_id.py ${{ github.head_ref }} ${{ inputs.GH_SHA }}

      - name: Download tf plan
        if: ${{ inputs.RUN_ON_PR }}
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          path: ${{ inputs.TF_PATH }}
          run-id: ${{ steps.get_run_id.outputs.run_id }}

      - name: PR Infracost report
        id: generate_report
        if: ${{ inputs.RUN_ON_PR }}
        run: |
          chmod +x ../scripts/*
          ../scripts/infracost_comment.sh

      - name: Format report
        if: ${{ inputs.RUN_ON_PR }}
        run: |
          REPORT_FILE=${{ steps.generate_report.outputs.report }}
          python ../scripts/infracost_report_format.py $REPORT_FILE
          echo "output=output.md" >> $GITHUB_OUTPUT

      - name: Infracost Comment
        if: ${{ inputs.RUN_ON_PR }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('terraform/output.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: ${{ steps.pr_number.outputs.pr_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: content
            })