name: Migration Tests

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      CLEAR_CACHE:
        required: false
        type: boolean
        default: false
      RUN_MIGRATIONS:
        required: false
        type: boolean
        default: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      REGISTRY:
        required: true

env:
  DEFAULT_DOCKER_TAG: ${{ github.repository }}
  REGISTRY: ${{ secrets.REGISTRY }}

jobs:
  run-migration-tests:
    runs-on: [ self-hosted, linux ]
    if: ${{ inputs.RUN_MIGRATIONS }}
    name: Migrations
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Pull image
        run: |
          COMMIT_ID="${GITHUB_SHA}"
          ORG="${GITHUB_REPOSITORY_OWNER}"
          REPOSITORY=$(echo "${GITHUB_REPOSITORY}" | sed "s|${ORG}/||g")

          docker pull ${{ secrets.REGISTRY }}/${REPOSITORY}:${GITHUB_SHA}
          docker tag  ${{ secrets.REGISTRY }}/${REPOSITORY}:${GITHUB_SHA} $DEFAULT_DOCKER_TAG
          docker run --rm --entrypoint "" ${{ secrets.REGISTRY }}/${REPOSITORY}:${GITHUB_SHA} scripts/run_tests.sh
      - name: Run migrations
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
        run: |
          chmod +x ./scripts/*
          ORG="${GITHUB_REPOSITORY_OWNER}"
          REPOSITORY=$(echo "${GITHUB_REPOSITORY}" | sed "s|${ORG}/||g")
          ./scripts/migrations_run.sh $REPOSITORY
      - name: Rollback migrations
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
        run: |
          ORG="${GITHUB_REPOSITORY_OWNER}"
          REPOSITORY=$(echo "${GITHUB_REPOSITORY}" | sed "s|${ORG}/||g")
          ./scripts/migrations_rollback.sh $REPOSITORY
      - name: Stop database
        if: ${{ always() }}
        run: |
          ORG="${GITHUB_REPOSITORY_OWNER}"
          REPOSITORY=$(echo "${GITHUB_REPOSITORY}" | sed "s|${ORG}/||g")
          ./scripts/stop_db.sh $REPOSITORY
      - name: Clear images
        if: ${{ inputs.CLEAR_CACHE }}
        run: |
          IMAGE_ID=$(docker images -q $DEFAULT_DOCKER_TAG)
          docker rmi -f $IMAGE_ID
