name: Unit-Tests

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      REGISTRY:
        required: true

jobs:
  run-unit-tests:
    runs-on: [self-hosted, linux]
    name: Run Migration tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Pull image
        run: |
          COMMIT_ID="${GITHUB_SHA}"
          ORG="${GITHUB_REPOSITORY_OWNER}"
          REPOSITORY=$(echo "${GITHUB_REPOSITORY}" | sed "s|${ORG}/||g")

          docker pull ${{ secrets.REGISTRY }}/${REPOSITORY}:${GITHUB_SHA}
          docker run --entrypoint "" ${{ secrets.REGISTRY }}/${REPOSITORY}:${GITHUB_SHA} scripts/run_tests.sh
      - name: Run migrations
        run: |
          REPOSITORY=$(echo "${GITHUB_REPOSITORY}" | sed "s|${ORG}/||g")
          ./scripts/migrations_run.sh $REPOSITORY
      - name: Rollback migrations
        run: |
          REPOSITORY=$(echo "${GITHUB_REPOSITORY}" | sed "s|${ORG}/||g")
          ./scripts/migrations_rollback.sh $REPOSITORY
      - name: Stop database
        if: always()
        run: |
          REPOSITORY=$(echo "${GITHUB_REPOSITORY}" | sed "s|${ORG}/||g")
          ./scripts/stop_db.sh $REPOSITORY
