name: Pre and Post deploy actions

on:
  workflow_call:
    inputs:
      ACTION:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string

env:
  REGION: ${{ inputs.AWS_REGION }}
  ENVIRONMENT: ${{ inputs.ENVIRONMENT }}

jobs:
  pre-post-deploy:
    name: Actions
    runs-on: [ self-hosted, linux, intuitivo ]
    concurrency:
      group: ${{ inputs.ACTION }}-deploy-${{ inputs.ENVIRONMENT }}-${{ inputs.AWS_REGION }}-${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run pre_deploy script
        if: ${{ inputs.ACTION == 'pre' }}
        run: |
          chmod +x ./scripts/*
          ./scripts/pre_deploy.sh
      - name: Run post_deploy script
        if: ${{ inputs.ACTION == 'post' }}
        run: |
          chmod +x ./scripts/*
          ./scripts/post_deploy.sh