name: Job configuration

on:
  workflow_call:
    inputs:
      DEFAULT_ENVIRONMENT:
        required: true
        type: string
      ENVIRONMENT:
        required: false
        type: string
    outputs:
      environment:
        description: "Current Environment"
        value: ${{ jobs.pre.outputs.environment }}
      event_name:
        description: "The name of the event that triggered the workflow run "
        value: ${{ jobs.pre.outputs.event_name }}

jobs:
  pre:
    name: Initial job configuration
    runs-on: [self-hosted, linux]
    outputs:
      environment: ${{ steps.set_env.outputs.env }}
      event_name: ${{ steps.event_info.outputs.event_name }}
    steps:
      - id: event_info
        name: Show context
        run: |
          echo "github=${{ github }}"
          echo "github.actor=${{ github.actor }}"
          echo "github.base_ref=${{ github.base_ref }}"
          echo "github.event_name=${{ github.event_name }}"
          echo "github.head_ref=${{ github.head_ref }}"
          echo "github.job=${{ github.job }}"
          echo "github.ref=${{ github.ref }}"
          echo "github.ref_name=${{ github.ref_name }}"
          echo "github.ref_type=${{ github.ref_type }}"
          echo "github.retention_days=${{ github.retention_days }}"
          echo "github.run_id=${{ github.run_id }}"
          echo "github.run_number=${{ github.run_number }}"
          echo "github.sha=${{ github.sha }}"

          echo "::set-output name=event_name::${{ github.event_name }}"
      - id: set_env
        name: Set environment
        run: |
          export ENV=${{ inputs.ENVIRONMENT || inputs.DEFAULT_ENVIRONMENT }}
          echo "::set-output name=env::$ENV"
