name: PR follow
'on':
  workflow_dispatch:
    inputs:
      ACTION:
        description: ''
        required: true
        default: list_pr
        type: choice
        options:
        - list_pr
        - update_branch
      BRANCH_NAME:
        description: ''
        required: true
        default: "delete_infra"
        type: string
      ENVIRONMENT:
        description: ''
        required: false
        default: ai
        type: choice
        options:
        - ai
        - core
        - wallet
        - infra
        - modules
env:
  BRANCH_NAME: ${{ inputs.BRANCH_NAME }}
  GITHUB_TOKEN: ${{ secrets.GGH_TOKEN }}
  SQUAD: ${{ inputs.ENVIRONMENT }}


jobs:
  list_pr:
    runs-on: [ self-hosted, linux, intuitivo ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd pr
          pip install -r requirements.txt
      - name: List pr
        if: ${{ inputs.ACTION == 'list_pr' }}
        run: |
          ls -a
          python ./terranator_pr.py

      - name: New Disposable Branch
        if: ${{ inputs.ACTION == 'update_branch' }}
        run: python open_delete_branch.py