name: PR follow
'on':
  workflow_dispatch:
    inputs:
      ACTION:
        description: ''
        required: true
        default: list_pr
        type: choice
        options:
        - list_pr
        - update_branch
      BRANCH_NAME:
        description: ''
        required: true
        default: "delete_infra"
        type: string
      ENVIRONMENT:
        description: ''
        required: false
        default: ai
        type: choice
        options:
        - ai
        - core
        - wallet
        - infra
        - modules
env:
  BRANCH_NAME: ${{ inputs.BRANCH_NAME }}
  GITHUB_TOKEN: ${{ secrets.GGH_TOKEN }}
  SQUAD: ${{ inputs.ENVIRONMENT }}

jobs:
  list_pr:
    runs-on: [ self-hosted, linux, intuitivo ]
    defaults:
      run:
        working-directory: pr

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: List pr
        if: ${{ inputs.ACTION == 'list_pr' }}
        run: |
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          python terranator_pr.py

      - name: New Disposable Branch
        if: ${{ inputs.ACTION == 'update_branch' }}
#        uses: intuitivo-ai/in2-actions//update_branch@action_update_branch
        uses: intuitivo-ai/in2-github-actions-test//update_branch@follow_pr
        with:
          gh_token : ${{ secrets.GGH_TOKEN }}
          new_branch_name: ${{ inputs.BRANCH_NAME }}