name: Pull Request
on:
  pull_request:
    types: [opened, ready_for_review, synchronize]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  clean_old_comments :
    name: Delete old Comments
    runs-on: [ self-hosted, linux ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get PR number
        id: pr_number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod -R +x ./scripts
          ./scripts/get_pr_number.sh
      - name: Delete old PR Comments
        if: ${{ steps.pr_number.outputs.pr_number != 0 }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./scripts/delete_pr_comments.sh')
            console.log(script({github, context}))
  build:
    name: Pull Request
    needs:
    - clean_old_comments
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      AWS_REGION: us-east-1
      CHECKOUT_IN2_REPOSITORIES: true
      CHECKOUT_IN2_REPOSITORY_NAMES: in2-react-components
      CLEAR_CACHE: true
      PUBLISH: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKER_BUILD_ARGS: FW_SECRET_KEY=${{ secrets.FW_SECRET_KEY }}
      REGISTRY: ${{ secrets.ECR_REGISTRY }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
  scan_image:
    name: Scan
    needs:
    - build
    uses: ./.github/workflows/show-ecr-vulnerabilities.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  terraform_plan:
    if: ${{ !github.event.pull_request.draft  }}
    name: Terraform plan
    strategy:
      fail-fast: false
      matrix:
        env:
        - development
        - devops-sandbox
        - production
        - showroom
        - staging
        region:
        - sa-east-1
        - us-east-1
    needs:
      - clean_old_comments
    uses: ./.github/workflows/terraform-plan.yml
    with:
      AWS_REGION: ${{matrix.region}}
      ENVIRONMENT: ${{matrix.env}}
      LAMBDA: true
      TF_PATH: terraform
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  infracost-report:
    name: Infracost Report
    needs:
    - terraform_plan
    uses: ./.github/workflows/infracost-report.yml
    with:
      RUN_ON_PR: true
      TF_PATH: terraform
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
