name: Approval-Deploy

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: false
        type: string
        default: us-east-1
      ENVIRONMENT:
        required: true
        type: string
      WORKFLOW_URL:
        required: true
        type: string
    outputs:
      approved:
        description: "Approval result"
        value: ${{ jobs.request_approval_job.outputs.approved }}
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

jobs:
  request_approval_job:
    runs-on: [ self-hosted, linux, intuitivo ]
    name: Request Approval Deploy
    outputs:
      approved: ${{ steps.request_approval.outputs.approved }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Check if approval is required
        id: check_approval
        run: |
          chmod -R +x ./scripts/
          ./scripts/request_approval_deploy.sh is_approval_required ${{ inputs.AWS_REGION }} ${{ inputs.ENVIRONMENT }}
      - name: Request approval
        id: request_approval
        run: |
          if [ ${{ steps.check_approval.outputs.approval_required }} = 'true' ]; then
            echo "Approval required because of the following reason: ${{ steps.check_approval.outputs.reason }}"
            chmod -R +x ./scripts/
            ./scripts/request_approval_deploy.sh request_deploy_approval ${{ inputs.WORKFLOW_URL }} ${{ github.repository }} ${{ inputs.ENVIRONMENT }}
          else
            echo "Approval not required"
            echo "approved=true" >> "$GITHUB_OUTPUT"
          fi
