name: Apply

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      TF_PATH:
        required: false
        type: string
        default: './'
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    name: Apply
    defaults:
      run:
        working-directory: ${{ inputs.TF_PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Init
        run: |
          terraform init -reconfigure -backend-config=${{ inputs.ENVIRONMENT }}.backend
      - name: Refresh state
        run: |
          export TF_VAR_commit_id="${GITHUB_SHA}"
          terraform apply -var-file=${{ inputs.ENVIRONMENT }}.tfvars -auto-approve -refresh-only
      - name: Plan
        run: |
          export TF_VAR_commit_id="${GITHUB_SHA}"
          terraform plan -var-file=${{ inputs.ENVIRONMENT }}.tfvars -input=false
      - name: Apply
        run: |
          export TF_VAR_commit_id="${GITHUB_SHA}"
          terraform apply -var-file=${{ inputs.ENVIRONMENT }}.tfvars -auto-approve
