name: Plan

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      COMMIT_ID:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  TF_VAR_commit_id: ${{GITHUB_SHA}}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    name: Plan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Init
        run: terraform init -reconfigure -backend-config=${{ inputs.ENVIRONMENT }}.backend
      - name: Validate
        run: terraform validate -json
      - name: Plan
        run: terraform plan -input=false -var-file=${{ inputs.ENVIRONMENT }}.tfvars
