name: Terraform Apply

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      LAMBDA:
        required: false
        type: boolean
        default: false
      TF_PATH:
        required: false
        type: string
        default: './'
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  terraform-apply:
    runs-on: [ self-hosted, linux ]
    environment: ${{ inputs.ENVIRONMENT }}
    concurrency:
      group: terraform-apply-${{ inputs.ENVIRONMENT }}
    name: Apply
    defaults:
      run:
        working-directory: ${{ inputs.TF_PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Create lambda zip files
        if: ${{ inputs.LAMBDA }}
        run: cd .. ; ./scripts/create_zip_files.sh ; cd -
      - name: Init
        run: |
          terraform init -reconfigure -backend-config=${{ inputs.ENVIRONMENT }}.backend
      - name: Refresh state
        run: |
          export TF_VAR_commit_id="${GITHUB_SHA}"
          terraform apply -var-file=${{ inputs.ENVIRONMENT }}.tfvars -input=false -auto-approve -refresh-only
      - name: Plan
        run: |
          export TF_VAR_commit_id="${GITHUB_SHA}"
          terraform plan -var-file=${{ inputs.ENVIRONMENT }}.tfvars -input=false
      - name: Apply
        id: apply
        run: |
          export TF_VAR_commit_id="${GITHUB_SHA}"
          terraform apply -var-file=${{ inputs.ENVIRONMENT }}.tfvars -input=false -auto-approve
      - name: Create Tag
        run: git tag "${{ inputs.ENVIRONMENT }}/${{ github.run_number }}" && git push -f origin "${{ inputs.ENVIRONMENT }}/${{ github.run_number }}"
      - name: Create Release
        #if: ${{ (github.event_name == 'push' && github.ref_name == 'main') && '${{ inputs.ENVIRONMENT }}' == 'staging' }}
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release/${{ github.run_number }}
          release_name: v${{ github.run_number }}
      - name: Notification
        if: always()
        run: |
          aws lambda invoke --function-name main-slash-bot --invocation-type Event --payload '{"source":"gh-actions","env":"${{ inputs.ENVIRONMENT }}","repository":"${{ github.event.repository.name }}","username":"${{ github.actor }}","status":"${{ steps.apply.outcome }}"}' response.json
