name: Terraform Plan

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      LAMBDA:
        required: false
        type: boolean
        default: false
      REQUIREMENTS:
        required: false
        type: boolean
        default: false
      TF_PATH:
        required: false
        type: string
        default: './'
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      PERSONAL_ACCESS_TOKEN:
        required: false

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  terraform-plan:
    runs-on: [ self-hosted, linux, intuitivo ]
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    concurrency:
      group: terraform-plan-${{ inputs.ENVIRONMENT }}-${{ inputs.AWS_REGION }}-${{ github.ref_name }}
    name: Plan
    defaults:
      run:
        working-directory: ${{ inputs.TF_PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name:  Check backend file
        id: check-file
        run: |
          if [ -e "${{ inputs.ENVIRONMENT }}-${{ inputs.AWS_REGION }}.backend" ]; then
            echo "El archivo de configuración del backend se encontró."
            echo "backendFile=true" >> $GITHUB_OUTPUT
          fi
      - name: Setup Terraform
        if: ${{ steps.check-file.outputs.backendFile == 'true' }}
        uses: hashicorp/setup-terraform@v2
      - name: Configure AWS credentials
        if: ${{ steps.check-file.outputs.backendFile == 'true' }}
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Create lambda zip files
        if: ${{ inputs.LAMBDA && steps.check-file.outputs.backendFile == 'true' }}
        run: |
          cd ..
          chmod +x ./scripts/*
          ./scripts/create_zip_files.sh
          cd -
      - name: Install workflow requirements
        if: ${{ inputs.REQUIREMENTS }}
        run: |
          cd ..
          chmod +x ./scripts/*
          ./scripts/requirements.sh
          cd -
      - name: Init
        if: ${{ steps.check-file.outputs.backendFile == 'true' }}
        run: |
          terraform init -reconfigure -backend-config=${{ inputs.ENVIRONMENT }}-${{ inputs.AWS_REGION }}.backend
      - name: Detect import template
        run: |
          original_filename="import-${{ inputs.ENVIRONMENT }}-${{ inputs.AWS_REGION }}.import"
          new_filename="import-${{ inputs.ENVIRONMENT }}-${{ inputs.AWS_REGION }}.tf"
          
          if [ -f "$original_filename" ]; then
            mv "$original_filename" "$new_filename"
            echo "Import file $new_filename created."
          else
            echo "No import file detected for ${{ inputs.ENVIRONMENT }} in region ${{ inputs.AWS_REGION }}."
          fi
      - name: Validate
        if: ${{ steps.check-file.outputs.backendFile == 'true' }}
        run: |
          terraform validate -json
      - name: Plan
        if: ${{ steps.check-file.outputs.backendFile == 'true' }}
        run: |
          export TF_VAR_commit_id="${GITHUB_SHA}" TF_VAR_gh_run_number="${{ github.run_number }}" TF_VAR_gh_run_attempt="${{ github.run_attempt }}"
          terraform plan -var-file=${{ inputs.ENVIRONMENT }}-${{ inputs.AWS_REGION }}.tfvars -input=false -lock=false