name: Unit-Tests

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      DEFAULT_DOCKER_TAG:
        required: false
        type: string
        default: in2etvo
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      REGISTRY:
        required: true

jobs:
  run-unit-tests:
    runs-on: [self-hosted, linux]
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Test
        run: |
          docker pull ${{ secrets.REGISTRY }}/${REPOSITORY}:${GITHUB_SHA}
          docker images
          docker run  ${{ secrets.REGISTRY }}/${REPOSITORY}:${GITHUB_SHA} scripts/run_tests.sh
